### ISSUE TITLE
cssHash missing chunks in production environment.

### ISSUE THREAD

**Issue by phyllisstein** [faceyspacey/babel-plugin-dual-import#1]
Hey there! On your advice I'm the new hotness a try. So far it seems to work great in development mode, but I'm having some trouble in prod. The only CSS chunk that's being added to the hash is `main`, and so it's failing to load assets from code-split chunks altogether.

###### Development
<img width="555" alt="screen shot 1" src="https://user-images.githubusercontent.com/2207980/27984346-42ffdbb6-63a2-11e7-8204-76454155136d.png">

###### Production
<img width="555" alt="screen shot" src="https://user-images.githubusercontent.com/2207980/27984348-476c553a-63a2-11e7-8061-64cfcd78c135.png">

It looks for all the world as though the chunk names aren't being applied correctly, based on what I'm seeing in the client stats:

```json
    {
      "name": "assets/css/931e9fdaec10ba94ee14b5241d081ab5.css",
      "size": 94273,
      "chunks": [
        9
      ],
      "chunkNames": [
        "main"
      ]
    },
    {
      "name": "assets/css/aa548c07b93a5b64ddc3581e2b860711.css",
      "size": 1457,
      "chunks": [
        7
      ],
      "chunkNames": []
    },
    {
      "name": "assets/css/81430d14053a00b408aaca07a410d3a7.css",
      "size": 29252,
      "chunks": [
        1
      ],
      "chunkNames": []
    },
    // ...etc
```

...but after looking at the code in this repo I'm not sure why that would be so. Inspecting the built assets, I see calls to `react-universal-component` that look like this in prod:

```js
var Five = __WEBPACK_IMPORTED_MODULE_11_react_universal_component___default.a((function () {
    return __WEBPACK_IMPORTED_MODULE_5_bluebird__["all"]([__webpack_require__.e/* import() */(41).then(__webpack_require__.bind(null, "6Bk0")), __WEBPACK_IMPORTED_MODULE_6_babel_plugin_dual_import_importCss_js___default.a('5')]).then((function (proms) {
        return proms[0];
    }));
}), {
    error: __WEBPACK_IMPORTED_MODULE_7_app_components_spinner__["a" /* ErrorSpinner */],
    loading: __WEBPACK_IMPORTED_MODULE_7_app_components_spinner__["c" /* ViewSpinner */],
    resolve: function resolve() {
        return /*require.resolve*/("6Bk0");
    }
});
```

...and like this in dev:

```js
var Five = __WEBPACK_IMPORTED_MODULE_11_react_universal_component___default.a(function () {
    return __WEBPACK_IMPORTED_MODULE_5_bluebird__["all"]([__webpack_require__.e/* import() */(19/*! 5 */).then(__webpack_require__.bind(null, /*! ./5 */ "./app/views/riot/chris/5.jsx")), __WEBPACK_IMPORTED_MODULE_6_babel_plugin_dual_import_importCss_js___default.a('5')]).then(function (proms) {
        return proms[0];
    });
}, {
    error: __WEBPACK_IMPORTED_MODULE_7_app_components_spinner__["a" /* ErrorSpinner */],
    loading: __WEBPACK_IMPORTED_MODULE_7_app_components_spinner__["c" /* ViewSpinner */],
    resolve: function resolve() {
        return /*require.resolve*/(/*! ./5 */ "./app/views/riot/chris/5.jsx");
    }
});
```

...but, again, can't quite account for the difference.

I've gisted my Webpack config [here](https://gist.github.com/phyllisstein/11917274d194502f89c0a54576836d2f) in case it's useful; I'm happy to provide any other troubleshooting information as well, if you can point me in the right direction.

Thanks in advance for your (continuing) guidance!

**Comment by phyllisstein** [comment]
🤕 🌴 I'd set `babel-loader` to disable comments in production; fixing this line did the trick: <https://gist.github.com/phyllisstein/11917274d194502f89c0a54576836d2f#file-build-webpack-config-js-L178>. 💖

**Comment by faceyspacey** [comment]
Congratuations @phyllisstein you're the first [i know of] to give this a try! I'm glad you got it working.

I'm assuming the issue is with webpack's Magic Comments in general. You think so? If so we should take that up with the Webpack team. 

If that's not something they fix for us, I probably should use `require.ensure` behind the scenes instead of `import()` since it has a `chunkName` option. I mean cuz the tradeoff you made now is that you have to ship a bunch of comments which adds bytes to builds, right?

**Comment by faceyspacey** [comment]
ps. dont forget to tweet and star. gotta get the world knowing about these solutions.

**Comment by phyllisstein** [comment]
It's working beautifully, HMR is much faster in dev and code splitting still works great in prod. The new constellation of packages even managed to integrate nicely with my finnicky use of `flushChunks` to serve initial asset bundles with HTTP/2 server push. We're live with the new setup at <https://1.ignotamagazine.com/> as of yesterday afternoon.

I defer to your judgment natch but personally wouldn't call this a Webpack issue. It was never really the Babel loader's responsibility to strip out comments---UglifyJS does that just fine once the bundle's all built---so fiddling with that option was bound to cause problems. I would also suggest in all humility that switching to `require.ensure` would be a step backwards; if this is eventually going to become part of `import`'s standard behavior, you probably gain some future flexibility by sticking to the newer API. It was a small glitch caused by my own overly manicured configuration, not worth making code changes over.

I will be sure to tweet a link to your Medium post once Twitter's awake again! Thanks for all your work putting this together.

**Comment by faceyspacey** [comment]
Oh got it, uglify still handles comment stripping for us. That was my main concern. 

Agreed on sticking with `import()`.

Nice 3D animated sidebar by the way. Let me know if you need anything else.
