### ISSUE TITLE
Is there an more complete demo of babel-plugin-dual-import?

### ISSUE THREAD

**Issue by lanjingling0510** [faceyspacey/babel-plugin-dual-import#2]
I can not find it

**Comment by faceyspacey** [comment]
All there is, is at the bottom of the article. You need to be using extract CSS chunks webpack plugin. That's probably the missing piece you're not privy to. Check that repo. It's also linked from the bottom of the article.

**Comment by lanjingling0510** [comment]
l get it . It seems necessary to correspond to the latest version of the extract CSS chunks webpack plugin and other packages.
