### ISSUE TITLE
Made a webpack plugin to inject __CSS_CHUNKS__ into HTML

### ISSUE THREAD

**Issue by m4r1vs** [faceyspacey/babel-plugin-dual-import#9]
I just made [`webpack-flush-chunks-html`](https://github.com/m4r1vs/webpack-flush-chunks-html), a webpack plugin that uses [`html-webpack-plugin`](https://github.com/jantimon/html-webpack-plugin) to inject all CSS files as `window.__CSS_CHUNKS__` into `index.js` for `dual-import` to be read. Would be cool if this plugin would get mentioned in the README so people can use it :)

**Comment by faceyspacey** [comment]
PR it and I will accept it.
